---
title: "ClimateData"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(ggplot2)
library(stringr)
library(readr)
library(dplyr)
library(corrplot)
library(car)
library(lattice)
library(caret)
library(readr)
library(tidyverse)
library(janitor)
library(leaflet)
library(sf)
library(mapview)
library(usmap)
climateData <- read_csv("climateData.csv")
climateData <- clean_names(climateData)
View(climateData)

```

```{r}
# #separating the green resources column into 5 columns 
# climateData <- climateData %>% 
#   separate(green_power_resources, into = c("energy1", "energy2", "energy3", "energy4", "energy5"), sep = ",")
# View(climateData)
```

```{r}
climateData$wind <- apply(climateData, 1, function(x)as.integer(any(grep('Wind',x))))
climateData$solar <- apply(climateData, 1, function(x)as.integer(any(grep('Solar',x))))
climateData$Biomas <- apply(climateData, 1, function(x)as.integer(any(grep('Biomas',x))))
climateData$Biogas <- apply(climateData, 1, function(x)as.integer(any(grep('Biogas',x))))
climateData$SmallHydro <- apply(climateData, 1, function(x)as.integer(any(grep('Small-hydro',x))))
climateData$Geothermal <- apply(climateData, 1, function(x)as.integer(any(grep('Geothermal',x))))
climateData$Various <- apply(climateData, 1, function(x)as.integer(any(grep('Various',x))))
View(climateData)

climateData$lat <-as.numeric(climateData$lat)
climateData$long <-as.numeric(climateData$long)


```


```{r}
#finding distinct colleges in dataset
#unique(climateData[c("college_name")])

#creating excel file
library("xlsx")
write.xlsx(unique(climateData[c("college_name")]), file = "uniquecolleges.xlsx", sheetName = "UNIQUE COLLEGES", append = FALSE)



```


```{r}
climate <- st_as_sf(climateData, coords = c("long", "lat"),  crs = 4326)
mapview(climate, map.types = "Stamen.Toner", popup = TRUE) 

```

```{r}
plot_usmap(data = climateData, values = "college_name",  color = "orange", labels=FALSE) +
  scale_fill_continuous( low = "white", high = orange,
                         name = "rank", label = scales::comma
  ) +
  theme(legend.position = "right") +
  theme(panel.background = element_rect(colour = "black"))

plot_usmap(
  regions = "states",
  data = climateData,
  values = "college_name"
)

```

```{r}
climateData %>% 
  group_by(college_name) %>% 
  ggplot(aes(x = college_name, y = rank)) +
  geom_line(color = "black") +
  scale_y_continuous(breaks = c(0,30)) +
  labs(title = "Tester",
       subtitle = "Test",
       x = element_blank(),
       y = element_blank()) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.line.x = element_blank(),
    axis.line.y = element_blank(),
    plot.title = element_text(size = 24),
    plot.subtitle = element_text(size = 18),
    strip.background = element_rect(color = "white")
  )
```

